### ISSUE TITLE
Notion API now allows for creating and updating of properties

### ISSUE THREAD

**Issue by csholmq** [Souvikns/Notion-Board#26]
![image](https://user-images.githubusercontent.com/1297882/133510480-1f9f5514-dfae-4e67-a600-752d3b1ed5b5.png)

https://developers.notion.com/reference/update-a-database

This could potentially automate some of the initial setting up of a database.

**Comment by Souvikns** [comment]
This is awesome now we don't need to manually create the properties. I will start working on this issue this weekend.

**Comment by Souvikns** [comment]
I haven't released a couple of things left, but I did something to solve this issue. 
On `workflow_dispatch` I am updating the notion database with all the required properties. I will release it after I update the documentation.

**Comment by Souvikns** [comment]
I have made a release, fixing this issue. But I think the issue with labels still persists

**Comment by csholmq** [comment]
I could confirm that the labels workaround fix did the trick. If the labels trigger finished before creating the issue the extra labels call in the create issue function still sets them correctly.

**Comment by Souvikns** [comment]
Yeah, it is working fine. New workflow runs are reacted in parallel that's why some runs fail.

**Comment by Souvikns** [comment]
Shall I close this issue, as I have created a `workflow_dispatch` to auto-setup the Notion database with the required properties?

**Comment by csholmq** [comment]
Fine by me. You call the shots 🙂
