### ISSUE TITLE
Problem triggering the action manually

### ISSUE THREAD

**Issue by Math-42** [Souvikns/Notion-Board#44]
The option to run the workflow does not appear when I select the notion board. Also, when I add a new issue the action gives the following error:

![image](https://user-images.githubusercontent.com/43853194/134048654-cf120223-e932-4498-bb19-640f3898a281.png)

**Comment by Souvikns** [comment]
Sorry for the inconvenience, I forgot to update the readme. 
It will work if you add `workflow_dispatch` here 
![image](https://user-images.githubusercontent.com/41781438/134111157-4e8d8db2-3df0-4e4a-91d0-9520e1e6fa45.png)


and instead on `@latest` use the latest version, like this 

![image](https://user-images.githubusercontent.com/41781438/134111311-d349be3f-192d-42fa-96bd-7354e2d474b6.png)


> This is should solve it your issue.

**Comment by Math-42** [comment]
thanks, it worked!
