### ISSUE TITLE
Would be nice to have a notion template to use for this Action 

### ISSUE THREAD

**Issue by Souvikns** [Souvikns/Notion-Board#48]

**Comment by DavidMc2021** [comment]
It would be nice to have both a notion template and a working notion page that hosted the current issues posted in this repository as well.

**Comment by Souvikns** [comment]
@DavidMc2021 I have made the notion template I was using to test public, I have also updated the docs a bit 

Here is the notion page link https://souvikns.notion.site/64bc98b98e6242c9bbc1cbedf9c93261?v=d40f6cc3d19a42a2ac3fb7e6a9e513cd

**Comment by DavidMc2021** [comment]
This looks great and lets people copy to see it in action! I think this issue can be closed.
